export type LocalPlayerBody={x:number;y:number;vx:number;vy:number;team:number;r:number;role?:string};
export type LocalVec={x:number;y:number};
export interface LocalP2Input{move:LocalVec;aim:LocalVec;pass:boolean;shoot:boolean;tackle:boolean;switchPlayer:boolean;sprint:boolean}
const norm=(x:number,y:number,fallback:LocalVec={x:-1,y:0})=>{const l=Math.hypot(x,y);return l>.001?{x:x/l,y:y/l}:fallback};
export function keyboardP2Input(keys:Record<string,boolean>,previousAim:LocalVec={x:-1,y:0}):LocalP2Input{const x=(keys.arrowright?1:0)-(keys.arrowleft?1:0),y=(keys.arrowdown?1:0)-(keys.arrowup?1:0),move=norm(x,y,{x:0,y:0}),moving=Math.hypot(x,y)>.1;return{move:moving?move:{x:0,y:0},aim:moving?move:previousAim,pass:Boolean(keys.enter),shoot:Boolean(keys.shift),tackle:Boolean(keys.control),switchPlayer:Boolean(keys["0"]),sprint:Boolean(keys["."])}}
export function chooseLocalPassTarget(players:LocalPlayerBody[],start:number,end:number,from:number,aim:LocalVec){const origin=players[from];if(!origin)return null;const direction=norm(aim.x,aim.y);let best:null|{index:number;score:number}=null;for(let i=start;i<end;i++){if(i===from)continue;const p=players[i];if(!p||p.team!==origin.team||p.role==="ARQ")continue;const dx=p.x-origin.x,dy=p.y-origin.y,d=Math.hypot(dx,dy)||1,dot=(dx/d)*direction.x+(dy/d)*direction.y;if(dot<-.1)continue;const score=dot*2.2-Math.min(1,d/520)*.75+(p.role==="DEL"?.08:0);if(!best||score>best.score)best={index:i,score}}return best?.index??null}
export function localPassVelocity(origin:LocalVec,target:LocalVec,power=.56){const dx=target.x-origin.x,dy=target.y-origin.y,l=Math.hypot(dx,dy)||1,speed=300+Math.max(0,Math.min(1,power))*300;return{x:dx/l*speed,y:dy/l*speed}}
export function localShotVelocity(origin:LocalVec,goalX:number,goalY:number,power=.8){const dx=goalX-origin.x,dy=goalY-origin.y,l=Math.hypot(dx,dy)||1,speed=450+Math.max(0,Math.min(1,power))*240;return{x:dx/l*speed,y:dy/l*speed}}
export function localSwitchCandidate(players:LocalPlayerBody[],start:number,end:number,current:number,ball:LocalVec){const currentTeam=players[current]?.team;let best=current,bestScore=Infinity;for(let i=start;i<end;i++){const p=players[i];if(!p||p.team!==currentTeam||p.role==="ARQ")continue;const distance=Math.hypot(p.x-ball.x,p.y-ball.y),penalty=i===current?24:0,score=distance+penalty;if(score<bestScore){bestScore=score;best=i}}return best}
export function edgePressed(current:boolean,previous:boolean){return current&&!previous}
