"use client";
import { useEffect,useRef,useState,type PointerEvent as ReactPointerEvent } from "react";
import { GamepadManagerV3 } from "./gamepad-v3";
import { chooseLocalPassTarget, edgePressed, keyboardP2Input, localPassVelocity, localShotVelocity, localSwitchCandidate } from "./local-multiplayer-v3";

type Lang="es"|"en";type Vec={x:number;y:number};type Body={x:number;y:number;vx:number;vy:number;team:0|1;r:number;role:"ARQ"|"CAMPO";active:boolean};
const W=960,H=540,L=48,R=912,T=72,B=468,CY=270,GT=210,GB=330;
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
const norm=(x:number,y:number,fallback:Vec={x:1,y:0})=>{const l=Math.hypot(x,y);return l>.001?{x:x/l,y:y/l}:fallback};
const initial=()=>{const result:Body[]=[];for(const team of [0,1] as const){const mirror=team===0?1:-1;result.push({x:team===0?120:840,y:CY,vx:0,vy:0,team,r:17,role:"ARQ",active:false});result.push({x:W/2-mirror*210,y:180,vx:0,vy:0,team,r:19,role:"CAMPO",active:true});result.push({x:W/2-mirror*210,y:360,vx:0,vy:0,team,r:19,role:"CAMPO",active:false})}return result};
const activeIndex=(bodies:Body[],team:0|1)=>bodies.findIndex(b=>b.team===team&&b.active);
const setActive=(bodies:Body[],team:0|1,index:number)=>bodies.forEach((b,i)=>{if(b.team===team)b.active=i===index});

export function LocalMatchV3({lang,onExit}:{lang:Lang;onExit:()=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),bodies=useRef<Body[]>(initial()),ball=useRef({x:W/2,y:CY,vx:0,vy:0,owner:null as number|null}),keys=useRef<Record<string,boolean>>({}),pads=useRef(new GamepadManagerV3()),aimP1=useRef<Vec>({x:1,y:0}),aimP2=useRef<Vec>({x:-1,y:0}),prevP1=useRef({pass:false,shoot:false,tackle:false,switch:false}),prevP2=useRef({pass:false,shoot:false,tackle:false,switch:false}),last=useRef(0),scoreRef=useRef<[number,number]>([0,0]),timeRef=useRef(180),ended=useRef(false);
 const [score,setScore]=useState<[number,number]>([0,0]),[time,setTime]=useState(180),[p2Controller,setP2Controller]=useState(false),[winner,setWinner]=useState<string|null>(null);
 const kickoff=()=>{bodies.current=initial();ball.current={x:W/2,y:CY,vx:0,vy:0,owner:null}};
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();keys.current[k]=true;if(["w","a","s","d","j","k","o","q","arrowup","arrowdown","arrowleft","arrowright","enter","shift","control","0"].includes(k))e.preventDefault()};const up=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=false};window.addEventListener("keydown",down);window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up);pads.current.reset()}},[]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;let raf=0;const loop=(now:number)=>{if(ended.current)return;const dt=Math.min(.034,(now-last.current)/1000||.016);last.current=now;timeRef.current=Math.max(0,timeRef.current-dt);if(Math.ceil(timeRef.current)!==time)setTime(Math.ceil(timeRef.current));const gamepads=pads.current.poll(),pad1=gamepads[0]??null,pad2=gamepads[1]??null;setP2Controller(Boolean(pad2));
 const p1KeyboardX=(keys.current.d?1:0)-(keys.current.a?1:0),p1KeyboardY=(keys.current.s?1:0)-(keys.current.w?1:0),p1Move=pad1?pad1.move:(Math.hypot(p1KeyboardX,p1KeyboardY)>.1?norm(p1KeyboardX,p1KeyboardY,{x:0,y:0}):{x:0,y:0});if(pad1&&Math.hypot(pad1.aim.x,pad1.aim.y)>.1)aimP1.current=pad1.aim;else if(Math.hypot(p1Move.x,p1Move.y)>.1)aimP1.current=p1Move;const p1={move:p1Move,pass:pad1?pad1.actions.PASS:Boolean(keys.current.j),shoot:pad1?pad1.actions.SHOOT:Boolean(keys.current.k),tackle:pad1?pad1.actions.TACKLE:Boolean(keys.current.o),switch:pad1?pad1.actions.SWITCH:Boolean(keys.current.q),sprint:pad1?pad1.actions.SPRINT:Boolean(keys.current[" "])};
 const p2Keyboard=keyboardP2Input(keys.current,aimP2.current),p2Move=pad2?pad2.move:p2Keyboard.move;if(pad2&&Math.hypot(pad2.aim.x,pad2.aim.y)>.1)aimP2.current=pad2.aim;else if(Math.hypot(p2Move.x,p2Move.y)>.1)aimP2.current=p2Move;const p2={move:p2Move,pass:pad2?pad2.actions.PASS:Boolean(p2Keyboard.actions.PASS),shoot:pad2?pad2.actions.SHOOT:Boolean(p2Keyboard.actions.SHOOT),tackle:pad2?pad2.actions.TACKLE:Boolean(p2Keyboard.actions.TACKLE),switch:pad2?pad2.actions.SWITCH:Boolean(p2Keyboard.actions.SWITCH_PLAYER),sprint:pad2?pad2.actions.SPRINT:false};
 const frames=[p1,p2];for(const team of [0,1] as const){const frame=frames[team],previous=team===0?prevP1.current:prevP2.current;let index=activeIndex(bodies.current,team);if(edgePressed(frame.switch,previous.switch)){const next=localSwitchCandidate(bodies.current,0,bodies.current.length,index,ball.current);if(next>=0&&bodies.current[next]?.team===team)setActive(bodies.current,team,next);else{let closest=index,d=Infinity;bodies.current.forEach((body,i)=>{if(body.team!==team||body.role==="ARQ")return;const value=Math.hypot(body.x-ball.current.x,body.y-ball.current.y);if(value<d){d=value;closest=i}});setActive(bodies.current,team,closest)}index=activeIndex(bodies.current,team)}const body=bodies.current[index];if(body){const accel=frame.sprint?1240:940;body.vx+=frame.move.x*accel*dt;body.vy+=frame.move.y*accel*dt;const speed=Math.hypot(body.vx,body.vy),max=frame.sprint?194:152;if(speed>max){body.vx=body.vx/speed*max;body.vy=body.vy/speed*max}const distance=Math.hypot(body.x-ball.current.x,body.y-ball.current.y);if(edgePressed(frame.tackle,previous.tackle)&&ball.current.owner!==null){const owner=bodies.current[ball.current.owner];if(owner&&owner.team!==team&&distance<62){ball.current.owner=index;ball.current.vx=0;ball.current.vy=0}}if(ball.current.owner===index&&edgePressed(frame.pass,previous.pass)){const direction=team===0?aimP1.current:aimP2.current,targetIndex=chooseLocalPassTarget(bodies.current,0,bodies.current.length,index,direction),validTarget=targetIndex!==null&&bodies.current[targetIndex]?.team===team?bodies.current[targetIndex]:null,target=validTarget??{x:body.x+direction.x*240,y:body.y+direction.y*240},v=localPassVelocity(ball.current,target,.62);ball.current.owner=null;ball.current.vx=v.x;ball.current.vy=v.y;if(validTarget)setActive(bodies.current,team,targetIndex!)}if(ball.current.owner===index&&edgePressed(frame.shoot,previous.shoot)){const direction=team===0?aimP1.current:aimP2.current,goalX=team===0?R+60:L-60,goalY=CY+direction.y*68,v=localShotVelocity(ball.current,goalX,goalY,.86);ball.current.owner=null;ball.current.vx=v.x;ball.current.vy=v.y}}if(team===0)prevP1.current={pass:frame.pass,shoot:frame.shoot,tackle:frame.tackle,switch:frame.switch};else prevP2.current={pass:frame.pass,shoot:frame.shoot,tackle:frame.tackle,switch:frame.switch}}
 bodies.current.forEach((body,i)=>{if(!body.active&&body.role==="CAMPO"){const team=body.team,ownBall=ball.current.owner!==null&&bodies.current[ball.current.owner]?.team===team,slot=i%3,baseX=team===0?(slot===1?330:420):(slot===1?630:540),baseY=slot===1?180:360,targetX=baseX+(ball.current.x-W/2)*(ownBall?.18:.09),targetY=baseY+(ball.current.y-CY)*.12,dx=targetX-body.x,dy=targetY-body.y,l=Math.hypot(dx,dy)||1;body.vx+=dx/l*430*dt;body.vy+=dy/l*430*dt}if(body.role==="ARQ"){const gx=body.team===0?105:855,gy=clamp(ball.current.y,GT+20,GB-20);body.vx+=(gx-body.x)*2.4*dt;body.vy+=(gy-body.y)*2.2*dt}const speed=Math.hypot(body.vx,body.vy),max=body.role==="ARQ"?96:body.active?200:140;if(speed>max){body.vx=body.vx/speed*max;body.vy=body.vy/speed*max}body.x=clamp(body.x+body.vx*dt,L+18,R-18);body.y=clamp(body.y+body.vy*dt,T+18,B-18);body.vx*=.88;body.vy*=.88});
 if(ball.current.owner===null){ball.current.x+=ball.current.vx*dt;ball.current.y+=ball.current.vy*dt;ball.current.vx*=Math.pow(.989,dt*60);ball.current.vy*=Math.pow(.989,dt*60);if(ball.current.y<T+9||ball.current.y>B-9){ball.current.vy*=-.74;ball.current.y=clamp(ball.current.y,T+9,B-9)}const inGoal=ball.current.y>GT&&ball.current.y<GB;if(inGoal&&(ball.current.x<L-2||ball.current.x>R+2)){const scoring:0|1=ball.current.x>W/2?0:1;scoreRef.current=[scoreRef.current[0]+(scoring===0?1:0),scoreRef.current[1]+(scoring===1?1:0)];setScore([...scoreRef.current]);kickoff()}else if(!inGoal&&(ball.current.x<L+8||ball.current.x>R-8)){ball.current.vx*=-.72;ball.current.x=clamp(ball.current.x,L+9,R-9)}let nearest=-1,d=Infinity;bodies.current.forEach((body,i)=>{const value=Math.hypot(body.x-ball.current.x,body.y-ball.current.y);if(value<d){d=value;nearest=i}});if(nearest>=0&&d<32&&Math.hypot(ball.current.vx,ball.current.vy)<410){ball.current.owner=nearest;ball.current.vx=0;ball.current.vy=0}}else{const owner=bodies.current[ball.current.owner];if(owner){const direction=owner.team===0?1:-1;ball.current.x=owner.x+direction*24;ball.current.y=owner.y}else ball.current.owner=null}
 if(timeRef.current<=0){ended.current=true;setWinner(scoreRef.current[0]===scoreRef.current[1]?(lang==="es"?"EMPATE":"DRAW"):scoreRef.current[0]>scoreRef.current[1]?"JUGADOR 1":"JUGADOR 2");return}
 ctx.clearRect(0,0,W,H);ctx.fillStyle="#05110a";ctx.fillRect(0,0,W,H);ctx.fillStyle="#13643a";ctx.fillRect(L,T,R-L,B-T);for(let i=0;i<10;i++){ctx.fillStyle=i%2?"rgba(255,255,255,.025)":"rgba(0,0,0,.04)";ctx.fillRect(L+i*(R-L)/10,T,(R-L)/10,B-T)}ctx.strokeStyle="rgba(255,255,255,.78)";ctx.lineWidth=3;ctx.strokeRect(L,T,R-L,B-T);ctx.beginPath();ctx.moveTo(W/2,T);ctx.lineTo(W/2,B);ctx.stroke();ctx.beginPath();ctx.arc(W/2,CY,62,0,Math.PI*2);ctx.stroke();ctx.strokeRect(L-24,GT,24,GB-GT);ctx.strokeRect(R,GT,24,GB-GT);bodies.current.forEach(body=>{ctx.fillStyle=body.team===0?"#d9ff45":"#7dd3fc";ctx.strokeStyle=body.active?"#fff":"rgba(0,0,0,.55)";ctx.lineWidth=body.active?4:3;ctx.beginPath();ctx.arc(body.x,body.y,body.r,0,Math.PI*2);ctx.fill();ctx.stroke();if(body.role==="ARQ"){ctx.fillStyle="#071008";ctx.font="bold 10px Arial";ctx.textAlign="center";ctx.fillText("GK",body.x,body.y+3)}});ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(ball.current.x,ball.current.y,9,0,Math.PI*2);ctx.fill();for(const team of [0,1] as const){const body=bodies.current[activeIndex(bodies.current,team)],a=team===0?aimP1.current:aimP2.current;if(body){ctx.strokeStyle=team===0?"#d9ff45":"#7dd3fc";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(body.x+a.x*25,body.y+a.y*25);ctx.lineTo(body.x+a.x*72,body.y+a.y*72);ctx.stroke()}}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf)},[lang,time]);
 const pointer=(e:ReactPointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*W,y=(e.clientY-r.top)/r.height*H,body=bodies.current[activeIndex(bodies.current,0)];if(body)aimP1.current=norm(x-body.x,y-body.y,aimP1.current)};
 return <div className="local-match-v3"><div className="local-v3-hud"><button onClick={onExit}>← {lang==="es"?"SALIR":"EXIT"}</button><div><b>JUGADOR 1</b><strong>{score[0]} — {score[1]}</strong><b>JUGADOR 2</b></div><span>{Math.floor(time/60)}:{String(time%60).padStart(2,"0")}</span></div><canvas ref={canvas} width={W} height={H} onPointerMove={pointer}/><div className="local-v3-help"><span><b>P1</b> WASD · J pase · K tiro · O robo · Q cambio · mouse apunta</span><span><b>P2</b> {p2Controller?"🎮 MANDO 2":"FLECHAS · Enter pase · Shift tiro · Ctrl robo · 0 cambio"}</span></div>{winner&&<div className="local-v3-finish"><small>{lang==="es"?"FINAL":"FULL TIME"}</small><h1>{winner}</h1><b>{score[0]} — {score[1]}</b><button onClick={()=>{scoreRef.current=[0,0];setScore([0,0]);timeRef.current=180;setTime(180);ended.current=false;setWinner(null);kickoff()}}>{lang==="es"?"REVANCHA":"REMATCH"}</button><button onClick={onExit}>{lang==="es"?"INICIO":"HOME"}</button></div>}</div>
}
