"use client";
import { useCallback,useEffect,useMemo,useRef,useState,type PointerEvent as ReactPointerEvent } from "react";
import { cloudClientV3, createRealtimeMatchChannelV3, type OnlineRoomV3 } from "./cloud-v3";

type Lang="es"|"en";
type Vec={x:number;y:number};
type NetInput={move:Vec;aim:Vec;pass:boolean;shoot:boolean;tackle:boolean;switchPlayer:boolean;sprint:boolean;seq:number};
type NetPlayer={x:number;y:number;vx:number;vy:number;team:0|1;keeper:boolean;active:boolean};
type Snapshot={seq:number;sentAt:number;clock:number;score:[number,number];ball:{x:number;y:number;vx:number;vy:number;owner:number|null};players:NetPlayer[];finished:boolean};
const W=960,H=540,L=48,R=912,T=72,B=468,CY=270,GOAL_TOP=210,GOAL_BOTTOM=330;
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
const normalized=(x:number,y:number,fallback:Vec={x:1,y:0})=>{const l=Math.hypot(x,y);return l>.001?{x:x/l,y:y/l}:fallback};
const blankInput=(team:0|1):NetInput=>({move:{x:0,y:0},aim:{x:team===0?1:-1,y:0},pass:false,shoot:false,tackle:false,switchPlayer:false,sprint:false,seq:0});
function initialPlayers(format:3|4){const players:NetPlayer[]=[];for(const team of [0,1] as const){for(let i=0;i<format;i++){const keeper=i===format-1,x=keeper?(team===0?85:875):(team===0?225+i*70:735-i*70),y=keeper?CY:130+(i%Math.max(1,format-1))*Math.min(125,250/Math.max(1,format-2));players.push({x,y,vx:0,vy:0,team,keeper,active:i===0})}}return players}
function chooseTarget(players:NetPlayer[],from:number,team:0|1,aim:Vec){const p=players[from];let best:number|null=null,bestScore=-Infinity;players.forEach((candidate,index)=>{if(index===from||candidate.team!==team||candidate.keeper)return;const dx=candidate.x-p.x,dy=candidate.y-p.y,d=Math.hypot(dx,dy)||1,dot=(dx/d)*aim.x+(dy/d)*aim.y,score=dot*2-Math.min(1,d/500)*.6;if(score>bestScore){bestScore=score;best=index}});return bestScore>-.1?best:null}
function nearestActive(players:NetPlayer[],team:0|1,ball:Vec){let best=-1,d=Infinity;players.forEach((p,i)=>{if(p.team!==team||p.keeper)return;const value=Math.hypot(p.x-ball.x,p.y-ball.y);if(value<d){d=value;best=i}});return best}
function setActive(players:NetPlayer[],team:0|1,index:number){players.forEach((p,i)=>{if(p.team===team)p.active=i===index})}

export function OnlineMatchV3({lang,room,userId,homeName,awayName,homeColor="#d9ff45",awayColor="#7dd3fc",onExit,onFinish}:{lang:Lang;room:OnlineRoomV3;userId:string;homeName:string;awayName:string;homeColor?:string;awayColor?:string;onExit:()=>void;onFinish:(score:[number,number],won:boolean)=>void}){
 const isHost=room.hostUserId===userId,myTeam:0|1=isHost?0:1;
 const canvas=useRef<HTMLCanvasElement>(null),channel=useRef<ReturnType<typeof createRealtimeMatchChannelV3>>(null),keys=useRef<Record<string,boolean>>({}),pointerAim=useRef<Vec>({x:myTeam===0?1:-1,y:0}),localInput=useRef<NetInput>(blankInput(myTeam)),remoteInput=useRef<NetInput>(blankInput(myTeam===0?1:0)),players=useRef<NetPlayer[]>(initialPlayers(room.format)),ball=useRef({x:W/2,y:H/2,vx:0,vy:0,owner:null as number|null}),scoreRef=useRef<[number,number]>([0,0]),clockRef=useRef(180),lastFrame=useRef(0),lastBroadcast=useRef(0),snapshotSeq=useRef(0),latestSnapshot=useRef<Snapshot|null>(null),previousButtons=useRef({pass:false,shoot:false,tackle:false,switchPlayer:false});
 const [status,setStatus]=useState<"CONNECTING"|"LIVE"|"RECONNECTING"|"FINISHED">("CONNECTING"),[score,setScore]=useState<[number,number]>([0,0]),[clock,setClock]=useState(180),[ping,setPing]=useState(0);
 const myTeamName=myTeam===0?homeName:awayName;
 const resetKickoff=useCallback(()=>{players.current=initialPlayers(room.format);ball.current={x:W/2,y:H/2,vx:0,vy:0,owner:null};},[room.format]);
 const send=useCallback(async(event:string,payload:object)=>{const ch=channel.current;if(!ch)return;try{await ch.send({type:"broadcast",event,payload:{...payload,from:userId}})}catch{}},[userId]);
 useEffect(()=>{const ch=createRealtimeMatchChannelV3(room.id,userId,event=>{if(event.from===userId)return;if(event.type==="input"&&isHost){remoteInput.current=event.payload.input as NetInput;setPing(Math.max(0,Date.now()-(Number(event.payload.sentAt)||Date.now())))}if(event.type==="snapshot"&&!isHost){const snap=event.payload.snapshot as Snapshot;if(snap&&snap.seq>(latestSnapshot.current?.seq??-1)){latestSnapshot.current=snap;setScore(snap.score);setClock(Math.ceil(snap.clock));setPing(Math.max(0,Date.now()-(Number(event.payload.sentAt)||Date.now())));if(snap.finished)setStatus("FINISHED")}}});channel.current=ch;setStatus(ch?"LIVE":"RECONNECTING");return()=>{try{void ch?.unsubscribe()}catch{}channel.current=null}},[room.id,userId,isHost]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();keys.current[k]=true;if(["w","a","s","d","j","k","o","q","shift"].includes(k))e.preventDefault()};const up=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=false};window.addEventListener("keydown",down);window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up)}},[]);
 useEffect(()=>{const timer=window.setInterval(()=>{const x=(keys.current.d?1:0)-(keys.current.a?1:0),y=(keys.current.s?1:0)-(keys.current.w?1:0),movement=Math.hypot(x,y)>.05?normalized(x,y,{x:0,y:0}):{x:0,y:0};localInput.current={move:movement,aim:pointerAim.current,pass:Boolean(keys.current.j),shoot:Boolean(keys.current.k),tackle:Boolean(keys.current.o),switchPlayer:Boolean(keys.current.q),sprint:Boolean(keys.current.shift),seq:localInput.current.seq+1};if(!isHost)void send("input",{input:localInput.current,sentAt:Date.now()})},33);return()=>window.clearInterval(timer)},[isHost,send]);
 useEffect(()=>{if(!isHost)return;let raf=0;const tick=(now:number)=>{const dt=Math.min(.034,(now-lastFrame.current)/1000||.016);lastFrame.current=now;if(status==="FINISHED")return;clockRef.current=Math.max(0,clockRef.current-dt);const inputs:[NetInput,NetInput]=myTeam===0?[localInput.current,remoteInput.current]:[remoteInput.current,localInput.current];for(const team of [0,1] as const){const input=inputs[team],active=players.current.findIndex(p=>p.team===team&&p.active),p=players.current[active];if(!p)continue;const previous=team===myTeam?previousButtons.current:{pass:false,shoot:false,tackle:false,switchPlayer:false};if(input.switchPlayer&&!previous.switchPlayer){const next=nearestActive(players.current,team,ball.current);if(next>=0)setActive(players.current,team,next)}const controlled=players.current.findIndex(player=>player.team===team&&player.active),body=players.current[controlled];if(!body)continue;const accel=input.sprint?1120:880;body.vx+=input.move.x*accel*dt;body.vy+=input.move.y*accel*dt;const speed=Math.hypot(body.vx,body.vy),max=input.sprint?184:146;if(speed>max){body.vx=body.vx/speed*max;body.vy=body.vy/speed*max}if(ball.current.owner===controlled&&input.pass&&!previous.pass){const targetIndex=chooseTarget(players.current,controlled,team,input.aim),target=targetIndex===null?{x:body.x+input.aim.x*220,y:body.y+input.aim.y*220}:players.current[targetIndex],dir=normalized(target.x-ball.current.x,target.y-ball.current.y,input.aim);ball.current.owner=null;ball.current.vx=dir.x*480;ball.current.vy=dir.y*480;if(targetIndex!==null)setActive(players.current,team,targetIndex)}if(ball.current.owner===controlled&&input.shoot&&!previous.shoot){const goalX=team===0?R+38:L-38,goalY=CY+input.aim.y*64,dir=normalized(goalX-ball.current.x,goalY-ball.current.y,input.aim);ball.current.owner=null;ball.current.vx=dir.x*650;ball.current.vy=dir.y*650}if(input.tackle&&!previous.tackle&&ball.current.owner!==null){const owner=players.current[ball.current.owner];if(owner&&owner.team!==team&&Math.hypot(owner.x-body.x,owner.y-body.y)<52){ball.current.owner=controlled;ball.current.vx=0;ball.current.vy=0}}if(team===myTeam)previousButtons.current={pass:input.pass,shoot:input.shoot,tackle:input.tackle,switchPlayer:input.switchPlayer}}
 for(let i=0;i<players.current.length;i++){const p=players.current[i];if(!p.active&&!p.keeper){const ownGoal=p.team===0?L:R,shapeX=p.team===0?250+(i%room.format)*65:710-(i%room.format)*65,targetX=ball.current.owner!==null&&players.current[ball.current.owner]?.team===p.team?shapeX:shapeX+(ball.current.x-W/2)*.12,targetY=135+(i%Math.max(1,room.format-1))*Math.min(130,250/Math.max(1,room.format-2));const dx=targetX-p.x,dy=targetY-p.y,l=Math.hypot(dx,dy)||1;p.vx+=dx/l*460*dt;p.vy+=dy/l*460*dt;if(Math.abs(p.x-ownGoal)<35)p.vx*=.8}if(p.keeper){const gx=p.team===0?82:878,targetY=clamp(ball.current.y,GOAL_TOP+20,GOAL_BOTTOM-20);p.vx+=(gx-p.x)*2.4*dt;p.vy+=(targetY-p.y)*2.2*dt}const speed=Math.hypot(p.vx,p.vy),max=p.keeper?98:142;if(speed>max){p.vx=p.vx/speed*max;p.vy=p.vy/speed*max}p.x=clamp(p.x+p.vx*dt,L+18,R-18);p.y=clamp(p.y+p.vy*dt,T+18,B-18);p.vx*=.88;p.vy*=.88}
 if(ball.current.owner===null){ball.current.x+=ball.current.vx*dt;ball.current.y+=ball.current.vy*dt;ball.current.vx*=Math.pow(.989,dt*60);ball.current.vy*=Math.pow(.989,dt*60);if(ball.current.y<T+9||ball.current.y>B-9){ball.current.vy*=-.72;ball.current.y=clamp(ball.current.y,T+9,B-9)}const goalZone=ball.current.y>GOAL_TOP&&ball.current.y<GOAL_BOTTOM;if(goalZone&&(ball.current.x<L-2||ball.current.x>R+2)){const scoring:0|1=ball.current.x>W/2?0:1;scoreRef.current=[scoreRef.current[0]+(scoring===0?1:0),scoreRef.current[1]+(scoring===1?1:0)];setScore(scoreRef.current);resetKickoff()}else if(!goalZone&&(ball.current.x<L+8||ball.current.x>R-8)){ball.current.vx*=-.7;ball.current.x=clamp(ball.current.x,L+9,R-9)}let closest=-1,d=Infinity;players.current.forEach((p,i)=>{const value=Math.hypot(p.x-ball.current.x,p.y-ball.current.y);if(value<d){d=value;closest=i}});if(closest>=0&&d<31&&Math.hypot(ball.current.vx,ball.current.vy)<430){ball.current.owner=closest;ball.current.vx=0;ball.current.vy=0}}else{const owner=players.current[ball.current.owner];if(owner){const face=owner.team===0?1:-1;ball.current.x=owner.x+face*24;ball.current.y=owner.y}else ball.current.owner=null}
 const finished=clockRef.current<=0;if(finished)setStatus("FINISHED");if(now-lastBroadcast.current>80||finished){lastBroadcast.current=now;const snapshot:Snapshot={seq:++snapshotSeq.current,sentAt:Date.now(),clock:clockRef.current,score:[...scoreRef.current] as [number,number],ball:{...ball.current},players:players.current.map(p=>({...p})),finished};void send("snapshot",{snapshot,sentAt:Date.now()});setClock(Math.ceil(clockRef.current))}if(finished){onFinish(scoreRef.current,scoreRef.current[myTeam]>scoreRef.current[myTeam===0?1:0]);return}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[isHost,myTeam,room.format,send,status,resetKickoff,onFinish]);
 useEffect(()=>{if(isHost)return;let raf=0;const drawLoop=()=>{const snap=latestSnapshot.current;if(snap){players.current=snap.players.map(p=>({...p}));ball.current={...snap.ball};scoreRef.current=snap.score;clockRef.current=snap.clock}raf=requestAnimationFrame(drawLoop)};raf=requestAnimationFrame(drawLoop);return()=>cancelAnimationFrame(raf)},[isHost]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;let raf=0;const render=()=>{ctx.clearRect(0,0,W,H);ctx.fillStyle="#06110b";ctx.fillRect(0,0,W,H);ctx.fillStyle="#12633a";ctx.fillRect(L,T,R-L,B-T);for(let i=0;i<10;i++){ctx.fillStyle=i%2?"rgba(255,255,255,.024)":"rgba(0,0,0,.035)";ctx.fillRect(L+i*(R-L)/10,T,(R-L)/10,B-T)}ctx.strokeStyle="rgba(255,255,255,.8)";ctx.lineWidth=3;ctx.strokeRect(L,T,R-L,B-T);ctx.beginPath();ctx.moveTo(W/2,T);ctx.lineTo(W/2,B);ctx.stroke();ctx.beginPath();ctx.arc(W/2,CY,62,0,Math.PI*2);ctx.stroke();ctx.strokeRect(L-25,GOAL_TOP,25,GOAL_BOTTOM-GOAL_TOP);ctx.strokeRect(R,GOAL_TOP,25,GOAL_BOTTOM-GOAL_TOP);players.current.forEach((p,i)=>{ctx.fillStyle=p.team===0?homeColor:awayColor;ctx.strokeStyle=p.active?(p.team===myTeam?"#fff":"#facc15"):"rgba(0,0,0,.55)";ctx.lineWidth=p.active?4:3;ctx.beginPath();ctx.arc(p.x,p.y,p.keeper?17:19,0,Math.PI*2);ctx.fill();ctx.stroke();if(p.keeper){ctx.fillStyle="#071008";ctx.font="bold 10px Arial";ctx.textAlign="center";ctx.fillText("GK",p.x,p.y+3)}});ctx.fillStyle="#fff";ctx.shadowColor="#000";ctx.shadowBlur=6;ctx.beginPath();ctx.arc(ball.current.x,ball.current.y,9,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;const active=players.current.find(p=>p.team===myTeam&&p.active);if(active){ctx.strokeStyle="#d9ff45";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(active.x+localInput.current.aim.x*24,active.y+localInput.current.aim.y*24);ctx.lineTo(active.x+localInput.current.aim.x*78,active.y+localInput.current.aim.y*78);ctx.stroke()}raf=requestAnimationFrame(render)};raf=requestAnimationFrame(render);return()=>cancelAnimationFrame(raf)},[homeColor,awayColor,myTeam]);
 const pointer=(e:ReactPointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*W,y=(e.clientY-r.top)/r.height*H,active=players.current.find(p=>p.team===myTeam&&p.active);if(!active)return;pointerAim.current=normalized(x-active.x,y-active.y,pointerAim.current)};
 const touchMove=(x:number,y:number)=>{localInput.current={...localInput.current,move:{x,y},aim:Math.hypot(x,y)>.1?normalized(x,y,pointerAim.current):pointerAim.current,seq:localInput.current.seq+1};pointerAim.current=localInput.current.aim};
 const pulse=(key:"pass"|"shoot"|"tackle"|"switchPlayer")=>{localInput.current={...localInput.current,[key]:true,seq:localInput.current.seq+1};if(!isHost)void send("input",{input:localInput.current,sentAt:Date.now()});window.setTimeout(()=>{localInput.current={...localInput.current,[key]:false,seq:localInput.current.seq+1};if(!isHost)void send("input",{input:localInput.current,sentAt:Date.now()})},90)};
 return <div className="online-match-v3"><div className="online-v3-hud"><button onClick={onExit}>← {lang==="es"?"SALIR":"EXIT"}</button><div><b>{homeName}</b><strong>{score[0]} — {score[1]}</strong><b>{awayName}</b></div><span>{Math.floor(clock/60)}:{String(clock%60).padStart(2,"0")} · {status} · {ping}ms</span></div><canvas ref={canvas} width={W} height={H} onPointerMove={pointer}/><div className="online-v3-touch"><div><button onPointerDown={()=>touchMove(0,-1)} onPointerUp={()=>touchMove(0,0)}>▲</button><button onPointerDown={()=>touchMove(-1,0)} onPointerUp={()=>touchMove(0,0)}>◀</button><button onPointerDown={()=>touchMove(0,1)} onPointerUp={()=>touchMove(0,0)}>▼</button><button onPointerDown={()=>touchMove(1,0)} onPointerUp={()=>touchMove(0,0)}>▶</button></div><div><button onClick={()=>pulse("pass")}>PAS</button><button className="shoot" onClick={()=>pulse("shoot")}>TIR</button><button onClick={()=>pulse("tackle")}>ROB</button><button onClick={()=>pulse("switchPlayer")}>CAM</button></div></div><small className="online-v3-note">{lang==="es"?`Jugás como ${myTeamName}. Servidor de partida: ${isHost?"este dispositivo":"rival"}. Sin boosts.`:`You play as ${myTeamName}. Match authority: ${isHost?"this device":"opponent"}. No boosts.`}</small></div>
}
