"use client";

import { useEffect,useMemo,useState } from "react";
import type { EconomyState } from "./economy-v2";
import { COSMETICS_V3, DIVISIONS, addTrainingStars, buyCosmetic, claimMission, divisionForRating, equipCosmetic, startCareer, xpNeededForLevel, type CosmeticKind, type MissionBoard, type MissionPeriod, type ProgressStateV3, type TrainingKind } from "./progression-v3";
import { cloudEnabledV3, createOnlineRoomV3, ensureCloudUserV3, findPlayerV3, leaderboardV3, requestFriendV3, signInWithEmailV3, type LeaderboardEntryV3, type OnlineRoomV3 } from "./cloud-v3";

type Tab="PROFILE"|"MISSIONS"|"SHOP"|"CAREER"|"TRAINING"|"RANKING"|"ONLINE";
type Lang="es"|"en";
const t=(lang:Lang,es:string,en:string)=>lang==="es"?es:en;
const pct=(value:number,target:number)=>Math.max(0,Math.min(100,value/Math.max(1,target)*100));

function MissionList({lang,board,period,onClaim}:{lang:Lang;board:MissionBoard;period:MissionPeriod;onClaim:(period:MissionPeriod,id:string)=>void}){
  return <div className="v3-mission-list">{board.missions.map(mission=>{const p=board.progress[mission.id]??{value:0,claimed:false},complete=p.value>=mission.target;return <article key={mission.id} className={`${complete?"complete":""} ${p.claimed?"claimed":""}`}><div><b>{mission.title}</b><p>{mission.description}</p><div className="v3-progress"><i style={{width:`${pct(p.value,mission.target)}%`}}/></div><small>{p.value}/{mission.target}</small></div><aside><span>+{mission.rewardMSC} MSC</span><span>+{mission.rewardXP} XP</span>{mission.rewardGems>0&&<span>+{mission.rewardGems} ◆</span>}<button disabled={!complete||p.claimed} onClick={()=>onClaim(period,mission.id)}>{p.claimed?t(lang,"COBRADA","CLAIMED"):t(lang,"COBRAR","CLAIM")}</button></aside></article>})}</div>
}

export function ProgressionHubV3({lang,state,economy,teams,onProgress,onEconomy,onBack,onStartTraining}:{lang:Lang;state:ProgressStateV3;economy:EconomyState;teams:Array<{id:string;name:string;region:string}>;onProgress:(next:ProgressStateV3)=>void;onEconomy:(next:EconomyState)=>void;onBack:()=>void;onStartTraining?:(kind:TrainingKind)=>void}){
  const [tab,setTab]=useState<Tab>("PROFILE"),[ranking,setRanking]=useState<LeaderboardEntryV3[]>([]),[cloudMessage,setCloudMessage]=useState(""),[email,setEmail]=useState(""),[search,setSearch]=useState(""),[roomCode,setRoomCode]=useState(""),[room,setRoom]=useState<OnlineRoomV3|null>(null);
  const division=divisionForRating(state.rating),nextDivision=DIVISIONS.find(item=>item.minimum>state.rating),xpNeed=xpNeededForLevel(state.level),accuracy=Math.round(state.stats.completedPasses/Math.max(1,state.stats.passes)*100);
  const countryTeams=useMemo(()=>teams.filter(team=>team.region==="Mundial"),[teams]);
  useEffect(()=>{if(tab!=="RANKING"||!cloudEnabledV3())return;leaderboardV3(50).then(setRanking)},[tab]);
  const claim=(period:MissionPeriod,id:string)=>{const result=claimMission(state,period,id);if(!result.rewardMSC&&!result.rewardXP&&!result.rewardGems)return;onProgress(result.state);onEconomy({...economy,msc:economy.msc+result.rewardMSC,gems:economy.gems+result.rewardGems})};
  const buy=(id:string)=>{const result=buyCosmetic(state,id,economy.msc);if(!result.ok)return;onProgress(result.state);onEconomy({...economy,msc:economy.msc-result.cost})};
  const sendMagicLink=async()=>{setCloudMessage(t(lang,"Enviando…","Sending…"));const result=await signInWithEmailV3(email);setCloudMessage(result.ok?t(lang,"Revisá tu correo para iniciar sesión.","Check your email to sign in."):result.error??"Error")};
  const addFriend=async()=>{const me=await ensureCloudUserV3();if(!me){setCloudMessage(t(lang,"No hay sesión cloud.","No cloud session."));return}const other=await findPlayerV3(search);if(!other){setCloudMessage(t(lang,"Jugador no encontrado.","Player not found."));return}const ok=await requestFriendV3(me.id,other.userId);setCloudMessage(ok?t(lang,"Solicitud enviada.","Friend request sent."):t(lang,"No se pudo enviar.","Could not send."))};
  const createRoom=async()=>{const me=await ensureCloudUserV3();if(!me){setCloudMessage(t(lang,"Activá tu cuenta primero.","Activate your account first."));return}const created=await createOnlineRoomV3(me.id,3);setRoom(created);setCloudMessage(created?t(lang,"Sala creada. Compartí el código.","Room created. Share the code."):t(lang,"No se pudo crear la sala.","Could not create room."))};
  return <div className="page-shell v3-hub"><button className="back" onClick={onBack}>← {t(lang,"INICIO","HOME")}</button><div className="v3-hero"><div><span className="eyebrow">MINI SOCCER COMPLETE · CENTRO MSC</span><h1>{t(lang,"TU CARRERA","YOUR JOURNEY")}</h1><p>{t(lang,"Progresión, estadísticas, tienda, entrenamiento y competición en un solo lugar.","Progression, stats, shop, training and competition in one place.")}</p></div><div className="v3-level-orb"><b>{state.level}</b><small>{t(lang,"NIVEL","LEVEL")}</small></div></div>
  <nav className="v3-tabs">{(["PROFILE","MISSIONS","SHOP","CAREER","TRAINING","RANKING","ONLINE"] as Tab[]).map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item==="PROFILE"?t(lang,"PERFIL","PROFILE"):item==="MISSIONS"?t(lang,"MISIONES","MISSIONS"):item==="SHOP"?t(lang,"COSMÉTICOS","COSMETICS"):item==="CAREER"?t(lang,"CARRERA","CAREER"):item==="TRAINING"?t(lang,"ENTRENAR","TRAIN"):item==="RANKING"?t(lang,"RANKING","RANKING"):t(lang,"ONLINE","ONLINE")}</button>)}</nav>

  {tab==="PROFILE"&&<div className="v3-profile-grid"><section className="v3-card featured"><span>{division.name}</span><h2>{state.rating} RP</h2><div className="v3-progress"><i style={{width:`${nextDivision?pct(state.rating-division.minimum,nextDivision.minimum-division.minimum):100}%`}}/></div><p>{nextDivision?t(lang,`${nextDivision.minimum-state.rating} puntos para ${nextDivision.name}`,`${nextDivision.minimum-state.rating} points to ${nextDivision.name}`):t(lang,"División máxima alcanzada","Top division reached")}</p></section><section className="v3-card"><span>XP</span><h2>{state.xp}/{xpNeed}</h2><div className="v3-progress"><i style={{width:`${pct(state.xp,xpNeed)}%`}}/></div><p>{t(lang,"El nivel desbloquea cosméticos; nunca mejora estadísticas dentro del partido.","Levels unlock cosmetics; they never improve match stats.")}</p></section><section className="v3-stat-grid">{[[t(lang,"Partidos","Matches"),state.stats.matches],[t(lang,"Victorias","Wins"),state.stats.wins],[t(lang,"Goles","Goals"),state.stats.goalsFor],[t(lang,"Vallas invictas","Clean sheets"),state.stats.cleanSheets],[t(lang,"Precisión de pase","Pass accuracy"),`${accuracy}%`],[t(lang,"Mejor racha","Best streak"),state.stats.bestWinStreak],[t(lang,"Torneos","Tournaments"),state.stats.tournaments],[t(lang,"Estrellas academia","Academy stars"),state.stats.trainingStars]].map(([label,value])=><div key={String(label)}><small>{label}</small><b>{value}</b></div>)}</section><section className="v3-card achievements"><h2>{t(lang,"LOGROS","ACHIEVEMENTS")}</h2><div>{state.achievements.length?state.achievements.map(id=><span key={id}>✓ {id.replaceAll("_"," ")}</span>):<p>{t(lang,"Todavía no desbloqueaste logros.","No achievements unlocked yet.")}</p>}</div></section></div>}

  {tab==="MISSIONS"&&<div className="v3-missions"><h2>{t(lang,"DIARIAS","DAILY")}</h2><MissionList lang={lang} board={state.daily} period="DAILY" onClaim={claim}/><h2>{t(lang,"SEMANALES","WEEKLY")}</h2><MissionList lang={lang} board={state.weekly} period="WEEKLY" onClaim={claim}/><h2>{t(lang,"ESPECIALES","SPECIAL")}</h2><MissionList lang={lang} board={state.special} period="SPECIAL" onClaim={claim}/></div>}

  {tab==="SHOP"&&<div><div className="v3-wallet"><b>{economy.msc.toLocaleString()} MSC</b><b>{economy.gems} ◆</b><span>{t(lang,"La tienda 3.0 es cosmética. Las ventajas de partido siguen separadas y no entran en competitivo online.","The 3.0 shop is cosmetic. Match boosts stay separate and are disabled in competitive online.")}</span></div><div className="v3-cosmetics">{COSMETICS_V3.map(item=>{const owned=state.ownedCosmetics.includes(item.id),equipped=state.equipped[item.kind]===item.id,locked=state.level<item.levelRequired;return <article key={item.id} className={`${item.rarity.toLowerCase()} ${equipped?"equipped":""}`}><span>{item.kind.replaceAll("_"," ")}</span><h3>{item.name}</h3><small>{item.rarity} · LV {item.levelRequired}</small><b>{item.priceMSC?`${item.priceMSC.toLocaleString()} MSC`:t(lang,"INICIAL","STARTER")}</b>{owned?<button disabled={equipped} onClick={()=>onProgress(equipCosmetic(state,item.id))}>{equipped?t(lang,"EQUIPADO","EQUIPPED"):t(lang,"EQUIPAR","EQUIP")}</button>:<button disabled={locked||economy.msc<item.priceMSC} onClick={()=>buy(item.id)}>{locked?`LV ${item.levelRequired}`:t(lang,"COMPRAR","BUY")}</button>}</article>})}</div></div>}

  {tab==="CAREER"&&<div className="v3-career">{state.career.active?<><section className="v3-card featured"><span>{t(lang,"TEMPORADA","SEASON")} {state.career.season}</span><h2>{countryTeams.find(team=>team.id===state.career.teamId)?.name??state.career.teamId}</h2><p>{t(lang,"Objetivo","Objective")}: {state.career.objective.replaceAll("_"," ")}</p></section><section className="v3-stat-grid">{[["PJ",state.career.played],["PTS",state.career.points],["G",state.career.wins],["E",state.career.draws],["P",state.career.losses],["GF",state.career.goalsFor],["GC",state.career.goalsAgainst]].map(([label,value])=><div key={String(label)}><small>{label}</small><b>{value}</b></div>)}</section><div className="v3-form">{state.career.form.map((value,index)=><b key={index} className={value}>{value}</b>)}</div></>:<><h2>{t(lang,"INICIAR CARRERA","START CAREER")}</h2><p>{t(lang,"Elegí un equipo. La carrera mantiene temporadas, puntos, forma y objetivos sin convertir el juego en un simulador de oficina.","Pick a team. Career tracks seasons, points, form and objectives without turning the game into a management spreadsheet.")}</p><div className="v3-team-grid">{countryTeams.map(team=><button key={team.id} onClick={()=>onProgress(startCareer(state,team.id))}>{team.name}</button>)}</div></>}</div>}

  {tab==="TRAINING"&&<div className="v3-training"><p>{t(lang,"Cada entrenamiento da de 0 a 3 estrellas según desempeño. Las estrellas sirven para logros y misiones, no para aumentar artificialmente la media.","Each drill awards 0–3 stars based on performance. Stars feed achievements and missions, not artificial player ratings.")}</p>{(["SHOOTING","PASSING","DRIBBLING","DEFENDING","KEEPER"] as TrainingKind[]).map(kind=><article key={kind}><span>{kind==="SHOOTING"?"◎":kind==="PASSING"?"→":kind==="DRIBBLING"?"◇":kind==="DEFENDING"?"◆":"▣"}</span><div><h3>{kind}</h3><p>{kind==="SHOOTING"?t(lang,"10 remates: precisión, potencia y colocación.","10 shots: accuracy, power and placement."):kind==="PASSING"?t(lang,"Objetivos móviles y pases al espacio.","Moving targets and through passes."):kind==="DRIBBLING"?t(lang,"Slalom y control de pelota.","Slalom and ball control."):kind==="DEFENDING"?t(lang,"Recuperá la pelota sin desordenarte.","Win the ball without losing shape."):t(lang,"Atajá una secuencia de remates.","Save a sequence of shots.")}</p></div><button onClick={()=>onStartTraining?onStartTraining(kind):onProgress(addTrainingStars(state,kind,1))}>{t(lang,"ENTRENAR","TRAIN")}</button></article>)}</div>}

  {tab==="RANKING"&&<div className="v3-ranking"><div className="v3-cloud-box"><h3>{t(lang,"CUENTA Y NUBE","ACCOUNT & CLOUD")}</h3><p>{cloudEnabledV3()?t(lang,"Supabase disponible. Podés vincular un correo y conservar progreso entre PC y celular.","Supabase is available. Link an email and keep progress across PC and mobile."):t(lang,"Cloud desactivado en este entorno; el guardado local sigue funcionando.","Cloud is disabled in this environment; local saving still works.")}</p><div><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@ejemplo.com"/><button disabled={!cloudEnabledV3()} onClick={sendMagicLink}>{t(lang,"VINCULAR","LINK")}</button></div>{cloudMessage&&<small>{cloudMessage}</small>}</div><div className="v3-leaderboard"><div className="head"><span>#</span><span>{t(lang,"JUGADOR","PLAYER")}</span><span>LV</span><span>RP</span><span>G</span></div>{ranking.map((entry,index)=><div key={entry.userId}><span>{index+1}</span><b>@{entry.handle}</b><span>{entry.level}</span><strong>{entry.rating}</strong><span>{entry.wins}</span></div>)}{!ranking.length&&<p>{t(lang,"El ranking aparecerá cuando haya perfiles sincronizados.","The ranking will appear when synced profiles exist.")}</p>}</div></div>}

  {tab==="ONLINE"&&<div className="v3-online"><section className="v3-card"><h2>{t(lang,"AMIGOS","FRIENDS")}</h2><p>{t(lang,"Buscá por @usuario y mandá una solicitud.","Search by @handle and send a request.")}</p><div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="usuario_msc"/><button onClick={addFriend}>{t(lang,"AGREGAR","ADD")}</button></div></section><section className="v3-card featured"><h2>{t(lang,"CROSSPLAY","CROSSPLAY")}</h2><p>{t(lang,"Las salas online usan una autoridad de partida y sincronización en tiempo real. Las ayudas que regalan goles quedan desactivadas en competitivo.","Online rooms use match authority and realtime synchronization. Goal-granting boosts are disabled in competitive play.")}</p>{room?<div className="v3-room-code"><small>{t(lang,"CÓDIGO DE SALA","ROOM CODE")}</small><b>{room.code}</b><span>{room.status}</span></div>:<button onClick={createRoom}>{t(lang,"CREAR SALA 3V3","CREATE 3V3 ROOM")}</button>}<div className="v3-join"><input value={roomCode} onChange={e=>setRoomCode(e.target.value.toUpperCase())} maxLength={6} placeholder="ABC123"/><button disabled={roomCode.length!==6}>{t(lang,"UNIRME","JOIN")}</button></div>{cloudMessage&&<small>{cloudMessage}</small>}</section></div>}
  </div>
}
