"use client";
import { useCallback,useEffect,useRef,useState,type PointerEvent as ReactPointerEvent } from "react";
import type { TrainingKind } from "./progression-v3";

type Lang="es"|"en";
type Point={x:number;y:number};
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
const dist=(a:Point,b:Point)=>Math.hypot(a.x-b.x,a.y-b.y);
const labels:Record<TrainingKind,[string,string]>={SHOOTING:["PRECISIÓN DE REMATE","SHOOTING ACCURACY"],PASSING:["PASE Y VISIÓN","PASSING & VISION"],DRIBBLING:["CONTROL Y SLALOM","CONTROL & SLALOM"],DEFENDING:["LECTURA DEFENSIVA","DEFENSIVE READING"],KEEPER:["REFLEJOS DE ARQUERO","KEEPER REFLEXES"]};

export function TrainingArenaV3({lang,kind,onFinish,onExit}:{lang:Lang;kind:TrainingKind;onFinish:(stars:number,score:number)=>void;onExit:()=>void}){
  const canvas=useRef<HTMLCanvasElement>(null),keys=useRef<Record<string,boolean>>({}),pointer=useRef<Point>({x:760,y:270}),player=useRef<Point>({x:145,y:270}),target=useRef<Point>({x:780,y:270}),ball=useRef<Point>({x:180,y:270}),velocity=useRef<Point>({x:0,y:0}),nextAction=useRef(0),checkpoint=useRef(0),last=useRef(0),running=useRef(true),scoreRef=useRef(0),attempts=useRef(0),success=useRef(0);
  const [seconds,setSeconds]=useState(30),[score,setScore]=useState(0),[message,setMessage]=useState(lang==="es"?"Preparado":"Ready");
  const resetTarget=useCallback((seed=0)=>{const y=115+((seed*137+Math.floor(performance.now()/120))%310);target.current={x:kind==="KEEPER"?790:760,y};},[kind]);
  const finish=useCallback(()=>{if(!running.current)return;running.current=false;const ratio=success.current/Math.max(1,attempts.current),raw=scoreRef.current,stars=raw>=900&&ratio>=.7?3:raw>=520&&ratio>=.48?2:raw>=220?1:0;onFinish(stars,raw)},[onFinish]);
  useEffect(()=>{running.current=true;scoreRef.current=0;attempts.current=0;success.current=0;player.current=kind==="KEEPER"?{x:795,y:270}:{x:145,y:270};ball.current={x:180,y:270};velocity.current={x:0,y:0};checkpoint.current=0;setSeconds(30);setScore(0);resetTarget(1);const down=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=true;if(e.code==="Space"){e.preventDefault();action()}};const up=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=false};window.addEventListener("keydown",down);window.addEventListener("keyup",up);const timer=window.setInterval(()=>setSeconds(value=>{if(value<=1){window.clearInterval(timer);window.setTimeout(finish,0);return 0}return value-1}),1000);return()=>{running.current=false;window.clearInterval(timer);window.removeEventListener("keydown",down);window.removeEventListener("keyup",up)}},[kind,finish,resetTarget]);
  const reward=(points:number,text:string)=>{scoreRef.current+=points;success.current++;setScore(scoreRef.current);setMessage(text);window.setTimeout(()=>setMessage(""),450)};
  const miss=(text:string)=>{setMessage(text);window.setTimeout(()=>setMessage(""),350)};
  const action=useCallback(()=>{if(!running.current)return;attempts.current++;if(kind==="SHOOTING"){const start={x:player.current.x+25,y:player.current.y},aim=pointer.current,l=Math.max(1,dist(start,aim));ball.current={...start};velocity.current={x:(aim.x-start.x)/l*720,y:(aim.y-start.y)/l*720};return}if(kind==="PASSING"){const start={x:player.current.x+22,y:player.current.y},aim=pointer.current,l=Math.max(1,dist(start,aim));ball.current={...start};velocity.current={x:(aim.x-start.x)/l*610,y:(aim.y-start.y)/l*610};return}if(kind==="DEFENDING"){if(dist(player.current,ball.current)<62){reward(120,lang==="es"?"RECUPERACIÓN":"TACKLE");ball.current={x:780,y:100+Math.random()*340};velocity.current={x:-240-Math.random()*110,y:(Math.random()-.5)*100};resetTarget(attempts.current);return}miss(lang==="es"?"FUERA DE DISTANCIA":"TOO FAR");return}if(kind==="KEEPER"){if(dist(player.current,ball.current)<78){reward(150,lang==="es"?"ATAJADA":"SAVE");ball.current={x:180,y:100+Math.random()*340};const aim={x:800,y:100+Math.random()*340},l=dist(ball.current,aim);velocity.current={x:(aim.x-ball.current.x)/l*460,y:(aim.y-ball.current.y)/l*460};return}miss(lang==="es"?"ANTICIPÁ EL TIRO":"READ THE SHOT")}},[kind,lang,resetTarget]);
  useEffect(()=>{const c=canvas.current;if(!c)return,ctx=c.getContext("2d")!;let raf=0;const cones:Point[]=[{x:270,y:160},{x:390,y:365},{x:510,y:155},{x:630,y:365},{x:745,y:200}];const draw=(now:number)=>{const dt=Math.min(.04,(now-last.current)/1000||.016);last.current=now;const left=(keys.current.a||keys.current.arrowleft)?-1:0,right=(keys.current.d||keys.current.arrowright)?1:0,up=(keys.current.w||keys.current.arrowup)?-1:0,down=(keys.current.s||keys.current.arrowdown)?1:0,l=Math.hypot(left+right,up+down)||1;if(kind==="DRIBBLING"||kind==="DEFENDING"||kind==="KEEPER"){const speed=kind==="KEEPER"?260:230;player.current.x=clamp(player.current.x+(left+right)/l*speed*dt,80,kind==="KEEPER"?820:850);player.current.y=clamp(player.current.y+(up+down)/l*speed*dt,85,455)}
      if(kind==="DRIBBLING"){const cp=cones[checkpoint.current];if(cp&&dist(player.current,cp)<43){checkpoint.current++;reward(95,lang==="es"?"CONTROL":"CONTROL");if(checkpoint.current>=cones.length){checkpoint.current=0;player.current={x:145,y:270};scoreRef.current+=160;setScore(scoreRef.current)}}}
      if(kind==="DEFENDING"&&now>=nextAction.current&&Math.hypot(velocity.current.x,velocity.current.y)<10){ball.current={x:790,y:100+Math.random()*340};const destination={x:80,y:100+Math.random()*340},dl=dist(ball.current,destination);velocity.current={x:(destination.x-ball.current.x)/dl*(230+Math.random()*130),y:(destination.y-ball.current.y)/dl*(230+Math.random()*130)};nextAction.current=now+1700}
      if(kind==="KEEPER"&&now>=nextAction.current&&Math.hypot(velocity.current.x,velocity.current.y)<10){ball.current={x:180,y:100+Math.random()*340};const destination={x:815,y:105+Math.random()*330},dl=dist(ball.current,destination);velocity.current={x:(destination.x-ball.current.x)/dl*(420+Math.random()*100),y:(destination.y-ball.current.y)/dl*(420+Math.random()*100)};attempts.current++;nextAction.current=now+1450}
      ball.current.x+=velocity.current.x*dt;ball.current.y+=velocity.current.y*dt;velocity.current.x*=Math.pow(.995,dt*60);velocity.current.y*=Math.pow(.995,dt*60);
      if(kind==="SHOOTING"&&velocity.current.x>0&&ball.current.x>730){const hit=dist(ball.current,target.current)<65;if(hit)reward(110+Math.max(0,Math.round(60-dist(ball.current,target.current))),lang==="es"?"¡AL BLANCO!":"ON TARGET!");else miss(lang==="es"?"AFUERA":"MISS");velocity.current={x:0,y:0};ball.current={x:180,y:270};resetTarget(attempts.current+1)}
      if(kind==="PASSING"&&velocity.current.x>0&&ball.current.x>700){const hit=dist(ball.current,target.current)<78;if(hit)reward(95+Math.max(0,Math.round(50-dist(ball.current,target.current)*.5)),lang==="es"?"PASE PRECISO":"ACCURATE PASS");else miss(lang==="es"?"PASE FALLADO":"MISSED PASS");velocity.current={x:0,y:0};ball.current={x:180,y:270};resetTarget(attempts.current+3)}
      if(kind==="KEEPER"&&ball.current.x>835){if(dist(player.current,ball.current)<74){reward(150,lang==="es"?"ATAJADA":"SAVE")}else miss(lang==="es"?"GOL":"GOAL");velocity.current={x:0,y:0};nextAction.current=now+650}
      if(kind==="DEFENDING"&&ball.current.x<55){miss(lang==="es"?"SE ESCAPÓ":"GOT THROUGH");velocity.current={x:0,y:0};nextAction.current=now+600}
      ctx.clearRect(0,0,960,540);ctx.fillStyle="#06120b";ctx.fillRect(0,0,960,540);ctx.fillStyle="#126238";ctx.fillRect(50,65,860,420);for(let i=0;i<10;i++){ctx.fillStyle=i%2?"rgba(255,255,255,.025)":"rgba(0,0,0,.035)";ctx.fillRect(50+i*86,65,86,420)}ctx.strokeStyle="rgba(255,255,255,.75)";ctx.lineWidth=3;ctx.strokeRect(50,65,860,420);ctx.beginPath();ctx.moveTo(480,65);ctx.lineTo(480,485);ctx.stroke();ctx.beginPath();ctx.arc(480,275,58,0,Math.PI*2);ctx.stroke();
      if(kind==="SHOOTING"||kind==="PASSING"){ctx.strokeStyle="#d9ff45";ctx.lineWidth=4;ctx.beginPath();ctx.arc(target.current.x,target.current.y,kind==="SHOOTING"?55:68,0,Math.PI*2);ctx.stroke();ctx.fillStyle="rgba(217,255,69,.12)";ctx.fill()}
      if(kind==="DRIBBLING")cones.forEach((cone,index)=>{ctx.fillStyle=index===checkpoint.current?"#d9ff45":"#f97316";ctx.beginPath();ctx.moveTo(cone.x,cone.y-15);ctx.lineTo(cone.x-12,cone.y+14);ctx.lineTo(cone.x+12,cone.y+14);ctx.closePath();ctx.fill()});
      if(kind==="KEEPER"){ctx.strokeStyle="#e5e7eb";ctx.lineWidth=5;ctx.strokeRect(790,155,70,230)}
      ctx.fillStyle="#d9ff45";ctx.beginPath();ctx.arc(player.current.x,player.current.y,20,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#071008";ctx.lineWidth=4;ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(ball.current.x,ball.current.y,9,0,Math.PI*2);ctx.fill();ctx.fillStyle="#111";ctx.beginPath();ctx.arc(ball.current.x+2,ball.current.y-1,3,0,Math.PI*2);ctx.fill();
      if((kind==="SHOOTING"||kind==="PASSING")&&Math.hypot(velocity.current.x,velocity.current.y)<20){ctx.strokeStyle="rgba(217,255,69,.55)";ctx.setLineDash([6,5]);ctx.beginPath();ctx.moveTo(player.current.x+20,player.current.y);ctx.lineTo(pointer.current.x,pointer.current.y);ctx.stroke();ctx.setLineDash([])}raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>cancelAnimationFrame(raf)},[kind,lang,resetTarget]);
  const pointerMove=(e:ReactPointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();pointer.current={x:(e.clientX-r.left)/r.width*960,y:(e.clientY-r.top)/r.height*540}};
  return <div className="training-v3-screen"><div className="training-v3-top"><button onClick={onExit}>← {lang==="es"?"SALIR":"EXIT"}</button><div><small>ACADEMIA MSC</small><h1>{labels[kind][lang==="es"?0:1]}</h1></div><strong>{seconds}s</strong></div><div className="training-v3-score"><span>{lang==="es"?"PUNTOS":"SCORE"} <b>{score}</b></span><em>{message}</em><span>{lang==="es"?"INTENTOS":"ATTEMPTS"} <b>{attempts.current}</b></span></div><canvas ref={canvas} width={960} height={540} onPointerMove={pointerMove} onPointerDown={e=>{pointerMove(e);action()}}/><div className="training-v3-help">{kind==="SHOOTING"||kind==="PASSING"?(lang==="es"?"MOUSE/TOQUE para apuntar · CLIC/ESPACIO para ejecutar":"MOUSE/TOUCH to aim · CLICK/SPACE to execute"):(lang==="es"?"WASD/FLECHAS para moverte · ESPACIO para intervenir":"WASD/ARROWS to move · SPACE to act")}</div></div>
}
