"use client";
import { useEffect,useRef,useState,type PointerEvent as ReactPointerEvent } from "react";

type Lang="es"|"en";
type Point={x:number;y:number};
const steps=["MOVE","AIM","PASS","SHOOT","TACKLE","SWITCH"] as const;
type Step=typeof steps[number];
const copy:Record<Step,[string,string,string,string]>={
 MOVE:["MOVETE","MOVE","Usá WASD/flechas o el joystick.","Use WASD/arrows or the joystick."],
 AIM:["APUNTÁ","AIM","Mové el mouse o dirigí el joystick hacia el objetivo.","Move the mouse or point the stick toward the target."],
 PASS:["HACÉ UN PASE","MAKE A PASS","Cargá y soltá PAS. En PC también podés usar tu tecla/clic configurado.","Hold and release PASS. On PC you can also use your configured key/click."],
 SHOOT:["REMATÁ","SHOOT","Usá TIR cuando tengas el arco enfrente.","Use SHOOT when you face the goal."],
 TACKLE:["RECUPERÁ","TACKLE","Usá ROB cerca del rival; no te tires desde lejos.","Use TACKLE near the opponent; don't lunge from far away."],
 SWITCH:["CAMBIÁ JUGADOR","SWITCH PLAYER","Usá CAM para tomar el jugador más conveniente.","Use SWITCH to take control of the best-positioned player."],
};

export function TutorialV3({lang,onComplete,onExit}:{lang:Lang;onComplete:()=>void;onExit:()=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),player=useRef<Point>({x:170,y:270}),aim=useRef<Point>({x:1,y:0}),keys=useRef<Record<string,boolean>>({}),last=useRef(0),startPointer=useRef<Point|null>(null);
 const [index,setIndex]=useState(0),[message,setMessage]=useState(""),[completed,setCompleted]=useState<Step[]>([]),step=steps[index]??"SWITCH";
 const advance=(done:Step)=>{if(completed.includes(done))return;setCompleted(value=>[...value,done]);setMessage(lang==="es"?"✓ BIEN":"✓ GOOD");window.setTimeout(()=>{setMessage("");if(index>=steps.length-1)onComplete();else setIndex(value=>value+1)},550)};
 useEffect(()=>{const down=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=true;if(step==="MOVE"&&["w","a","s","d","arrowup","arrowdown","arrowleft","arrowright"].includes(e.key.toLowerCase()))advance("MOVE");if(step==="PASS"&&(e.key.toLowerCase()==="j"||e.code==="Space"))advance("PASS");if(step==="SHOOT"&&(e.key.toLowerCase()==="k"||e.key.toLowerCase()==="x"))advance("SHOOT");if(step==="TACKLE"&&(e.key.toLowerCase()==="o"||e.key.toLowerCase()==="c"))advance("TACKLE");if(step==="SWITCH"&&(e.key.toLowerCase()==="q"||e.key.toLowerCase()==="tab"))advance("SWITCH")};const up=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=false};window.addEventListener("keydown",down);window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up)}},[step,index,completed]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;let raf=0;const loop=(now:number)=>{const dt=Math.min(.04,(now-last.current)/1000||.016);last.current=now;const x=(keys.current.d||keys.current.arrowright?1:0)-(keys.current.a||keys.current.arrowleft?1:0),y=(keys.current.s||keys.current.arrowdown?1:0)-(keys.current.w||keys.current.arrowup?1:0),l=Math.hypot(x,y)||1;player.current.x=Math.max(90,Math.min(870,player.current.x+x/l*220*dt));player.current.y=Math.max(95,Math.min(445,player.current.y+y/l*220*dt));ctx.clearRect(0,0,960,540);ctx.fillStyle="#06120b";ctx.fillRect(0,0,960,540);ctx.fillStyle="#14643a";ctx.fillRect(55,70,850,400);for(let i=0;i<10;i++){ctx.fillStyle=i%2?"rgba(255,255,255,.025)":"rgba(0,0,0,.04)";ctx.fillRect(55+i*85,70,85,400)}ctx.strokeStyle="rgba(255,255,255,.78)";ctx.lineWidth=3;ctx.strokeRect(55,70,850,400);ctx.beginPath();ctx.moveTo(480,70);ctx.lineTo(480,470);ctx.stroke();ctx.beginPath();ctx.arc(480,270,62,0,Math.PI*2);ctx.stroke();ctx.strokeRect(840,190,65,160);ctx.fillStyle="#d9ff45";ctx.beginPath();ctx.arc(player.current.x,player.current.y,21,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#071008";ctx.lineWidth=4;ctx.stroke();const tip={x:player.current.x+aim.current.x*82,y:player.current.y+aim.current.y*82};ctx.strokeStyle="#d9ff45";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(player.current.x+aim.current.x*24,player.current.y+aim.current.y*24);ctx.lineTo(tip.x,tip.y);ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(player.current.x+30,player.current.y+10,9,0,Math.PI*2);ctx.fill();ctx.strokeStyle="rgba(217,255,69,.75)";ctx.setLineDash([6,5]);ctx.beginPath();ctx.arc(770,270,46,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf)},[]);
 const pointerMove=(e:ReactPointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect(),world={x:(e.clientX-r.left)/r.width*960,y:(e.clientY-r.top)/r.height*540},dx=world.x-player.current.x,dy=world.y-player.current.y,l=Math.hypot(dx,dy)||1;aim.current={x:dx/l,y:dy/l};if(step==="AIM"){if(!startPointer.current)startPointer.current=world;else if(Math.hypot(world.x-startPointer.current.x,world.y-startPointer.current.y)>35)advance("AIM")}};
 const touchMove=(dx:number,dy:number)=>{player.current.x=Math.max(90,Math.min(870,player.current.x+dx*20));player.current.y=Math.max(95,Math.min(445,player.current.y+dy*20));if(step==="MOVE")advance("MOVE");if(step==="AIM"){const l=Math.hypot(dx,dy)||1;aim.current={x:dx/l,y:dy/l};advance("AIM")}};
 const action=(name:Step)=>{if(step===name)advance(name)};
 return <div className="tutorial-v3-screen"><div className="tutorial-v3-head"><button onClick={onExit}>← {lang==="es"?"SALIR":"EXIT"}</button><div><small>TUTORIAL MSC</small><h1>{copy[step][lang==="es"?0:1]}</h1><p>{copy[step][lang==="es"?2:3]}</p></div><strong>{index+1}/{steps.length}</strong></div><div className="tutorial-v3-track">{steps.map((item,i)=><i key={item} className={i<index?"done":i===index?"active":""}/>)}</div><canvas ref={canvas} width={960} height={540} onPointerMove={pointerMove}/><div className="tutorial-v3-mobile"><div className="tutorial-pad"><button onClick={()=>touchMove(0,-1)}>▲</button><button onClick={()=>touchMove(-1,0)}>◀</button><button onClick={()=>touchMove(0,1)}>▼</button><button onClick={()=>touchMove(1,0)}>▶</button></div><div className="tutorial-actions"><button onClick={()=>action("PASS")}>PAS</button><button onClick={()=>action("SHOOT")}>TIR</button><button onClick={()=>action("TACKLE")}>ROB</button><button onClick={()=>action("SWITCH")}>CAM</button></div></div>{message&&<div className="tutorial-v3-good">{message}</div>}</div>
}
