import assert from "node:assert/strict";
import test from "node:test";
import { DEFAULT_PROGRESS_V3, applyProgressMatch, buyCosmetic, claimMission, divisionForRating, equipCosmetic, parseProgressV3, startCareer, xpNeededForLevel } from "../app/progression-v3.ts";

const fresh=()=>parseProgressV3(null,new Date("2026-08-25T12:00:00Z"));

test("XP levels preserve overflow",()=>{const need=xpNeededForLevel(1);const state={...fresh(),xp:need-10};const result=applyProgressMatch(state,{played:true,won:true,drew:false,goalsFor:2,goalsAgainst:0,completedPasses:10,difficulty:"Normal"},new Date("2026-08-25T12:00:00Z"));assert.equal(result.state.level,2);assert.ok(result.state.xp>=0)});
test("division thresholds",()=>{assert.equal(divisionForRating(0).name,"Bronce III");assert.equal(divisionForRating(1600).name,"Oro III");assert.equal(divisionForRating(5000).name,"Élite MSC")});
test("real match updates history streak team and achievements",()=>{const result=applyProgressMatch(fresh(),{played:true,won:true,drew:false,goalsFor:3,goalsAgainst:0,completedPasses:15,passes:18,difficulty:"Profesional",teamId:"arg",maxDeficit:1});assert.equal(result.state.stats.matches,1);assert.equal(result.state.stats.wins,1);assert.equal(result.state.stats.cleanSheets,1);assert.equal(result.state.stats.hatTricks,1);assert.equal(result.state.stats.teamsUsed.arg,1);assert.ok(result.state.achievements.includes("first_goal"));assert.ok(result.state.achievements.includes("hat_trick"));assert.ok(result.reward.ratingDelta>0)});
test("simulated matches create no progression",()=>{const result=applyProgressMatch(fresh(),{played:false,won:true,drew:false,goalsFor:1,goalsAgainst:0,completedPasses:0,difficulty:"Normal"});assert.equal(result.state.stats.matches,0);assert.equal(result.state.rating,0);assert.equal(result.reward.xp,0)});
test("missions are proportional and claim once",()=>{let state=fresh();state=applyProgressMatch(state,{played:true,won:true,drew:false,goalsFor:5,goalsAgainst:0,completedPasses:25,difficulty:"Normal"}).state;state=applyProgressMatch(state,{played:true,won:false,drew:false,goalsFor:0,goalsAgainst:1,completedPasses:4,difficulty:"Normal"}).state;const mission=state.daily.missions.find(m=>m.id==="daily_play_2");assert.ok(mission);assert.ok(mission.rewardMSC<500);const first=claimMission(state,"DAILY","daily_play_2");assert.equal(first.rewardMSC,120);const second=claimMission(first.state,"DAILY","daily_play_2");assert.equal(second.rewardMSC,0)});
test("cosmetics require level balance and remain owned",()=>{const state={...fresh(),level:30};const purchase=buyCosmetic(state,"hud_neon",2000);assert.equal(purchase.ok,true);assert.equal(purchase.cost,1600);assert.ok(purchase.state.ownedCosmetics.includes("hud_neon"));const equipped=equipCosmetic(purchase.state,"hud_neon");assert.equal(equipped.equipped.HUD,"hud_neon");assert.equal(buyCosmetic(equipped,"hud_neon",99999).ok,false)});
test("career accumulates table points",()=>{let state=startCareer(fresh(),"arg");state=applyProgressMatch(state,{played:true,won:true,drew:false,goalsFor:2,goalsAgainst:1,completedPasses:12,difficulty:"Normal",teamId:"arg"}).state;assert.equal(state.career.points,3);assert.equal(state.career.played,1);assert.deepEqual(state.career.form,["W"])});
test("invalid storage returns safe defaults",()=>{const parsed=parseProgressV3("invalid-json",new Date("2026-08-25T12:00:00Z"));assert.equal(parsed.version,3);assert.equal(parsed.level,1);assert.deepEqual(parsed.ownedCosmetics,DEFAULT_PROGRESS_V3.ownedCosmetics)});
